In [2]:
import numpy as np

In [4]:
a = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [6]:
# Get a specific element
a[0, 3]

4

In [7]:
# Get a specific row
a[1, :]

array([ 7,  8,  9, 10, 11, 12])

In [8]:
# Get a specific column
a[:, 3]

array([ 4, 10])

In [9]:
# Get something more fancy
a[0, 1:-1:2]

array([2, 4])

In [10]:
# Replace an element
a[0,0] = 3
print(a)

[[ 3  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [11]:
# Replace a row or column
a[:, 3] = 5
a[0, :] = [3, 5, 5,5,5,5]
print(a)

[[ 3  5  5  5  5  5]
 [ 7  8  9  5 11 12]]
