In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])

In [4]:
print(a)

[1 2 3]


In [18]:
b = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

In [19]:
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [8]:
# Get Dimensions
a.ndim

1

In [9]:
b.ndim

2

In [11]:
# Get Shape
a.shape

(3,)

In [12]:
b.shape

(2, 3)

In [15]:
# Get Type
a.dtype

dtype('int64')

In [16]:
# Get Size
a.itemsize

8

In [17]:
# Get Total Size
a.nbytes

24